// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkfvnueufzqvctfxjira.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZnZudWV1ZnpxdmN0ZnhqaXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNDcyNzMsImV4cCI6MjA3MDYyMzI3M30.ld-QaPoqMHCdIfCRFSpQJ1FVq-6VDVppBIzFtKz6m1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});